<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Task.Application.Shared\Task.Application.Shared.csproj" />
    <ProjectReference Include="..\Task.Core\Task.Core.csproj" />
    <ProjectReference Include="..\Task.DataAccess\Task.DataAccess.csproj" />
    <ProjectReference Include="..\Task.EventBus\Task.EventBus.csproj" />
  </ItemGroup>
</Project>
