<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\" />
    <None Remove="Abstraction\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Task.Core.Shared\Task.Core.Shared.csproj" />
    <ProjectReference Include="..\Task.Shared\Task.Shared.csproj" />
  </ItemGroup>
</Project>
